In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans,AffinityPropagation
from sklearn import metrics
plt.style.use('ggplot')
%matplotlib inline
data=pd.read_csv('data.csv')
num_data =pd.read_csv('num_data.csv')

In [8]:
model=KMeans(n_clusters=8).fit(num_data)
prediction = model.predict(num_data)
centers = model.cluster_centers_
print(prediction[:20])

[5 0 5 0 0 0 5 0 0 0 5 0 0 0 0 0 0 0 5 0]


In [15]:
centers

array([[0.62368421, 1.        , 0.17181451, 0.86746988, 0.80597015,
        0.99702233, 1.        , 0.58388149, 1.        ],
       [0.78947368, 0.34469585, 0.15884603, 0.8313253 , 0.84079602,
        0.99602978, 0.41666667, 0.43819497, 0.16279223],
       [0.56578947, 0.26980821, 0.10263613, 0.78313253, 0.67661692,
        0.99851117, 0.5       , 0.43746689, 0.18157282],
       [0.52631579, 0.43595955, 0.08872058, 0.81927711, 0.64676617,
        0.99900744, 0.33333333, 0.5507273 , 0.22081072],
       [0.52631579, 0.11665636, 0.04539183, 0.79518072, 0.47761194,
        0.99702233, 0.91666667, 0.71758717, 0.08377315],
       [0.44736842, 0.14225429, 0.08814598, 0.69879518, 0.6318408 ,
        0.99851117, 0.41666667, 0.29961542, 0.14225429],
       [0.47368421, 0.2720765 , 0.12633966, 0.84337349, 0.48258706,
        0.99950372, 0.41666667, 0.38024574, 0.2720765 ],
       [0.44736842, 0.27738103, 0.54946196, 0.95180723, 0.60199005,
        0.99950372, 0.58333333, 0.37352914, 0.13874865],


In [14]:
model = AffinityPropagation().fit(num_data)
prediction = model.predict(num_data)
centers = model.cluster_centers_
model.cluster_centers_indices_
print(prediction[:20])

C:\Softwares\Python3\lib\site-packages\sklearn\cluster\_affinity_propagation.py:148: FutureWarning: 'random_state' has been introduced in 0.23. It will be set to None starting from 1.0 (renaming of 0.25) which means that results will differ at every function call. Set 'random_state' to None to silence this warning, or to 0 to keep the behavior of versions <0.23.
  warnings.warn(


[ 0  1  9  1  5  2  4  3 18  5 17  2  2  2  5  3  1  2  9  2]


In [11]:
labels = model.labels_
metrics.silhouette_score(num_data, labels, metric='euclidean')

0.13765506742891104